name: "Create Conan Package"
on: push

jobs:
  build_linux:
    name: "Build Linux"
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@master
    with:
      image: "ghcr.io/tereius/conan-ubuntu:latest"
      runs-on: self-hosted
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan

  build_windows:
    name: "Build Windows"
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@master
    with:
      image: "ghcr.io/tereius/conan-wine:latest"
      runs-on: self-hosted
      conan_host_profile: "windowsMinGW"
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan
