name: "Create Conan Package"
on: push

jobs:
  build_linux:
    name: "Linux"
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@master
    with:
      image: "ghcr.io/tereius/conan-ubuntu:latest"
      runs-on: self-hosted
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan

  build_windows:
    name: "Windows"
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@master
    with:
      image: "ghcr.io/tereius/conan-wine:latest"
      runs-on: self-hosted
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan

  upload_recipe:
    name: "Finalize"
    uses: Privatehive/conan-workflows/.github/workflows/uploadRecipe.yml@master
    needs: [build_linux, build_windows]
    if: ${{ success() }}
    secrets: inherit
    with:
      conan_upload_remote: https://conan.privatehive.de/artifactory/api/conan/public-conan
